package com.example.orderservice.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * DOMAIN MODEL (Entity)
 * ======================
 *
 * This represents the CORE BUSINESS ENTITY in your domain.
 *
 * WHAT IS IT?
 * - Represents an Order in the business domain
 * - Contains ALL data about an order (even internal fields not exposed via API)
 * - In a real app with database: would have @Entity annotation (JPA)
 * - Lives in the service layer and below
 *
 * WHY SEPARATE FROM DTO?
 * - Domain models have business logic and internal state
 * - DTOs are just data transfer containers (no logic)
 * - Domain can evolve independently from API contracts
 * - You might store more data internally than you expose via API
 *
 * EXAMPLE:
 * - Domain model might have: paymentStatus, internalNotes, auditTrail
 * - DTO (API request) only has: customerId, items
 *
 * DESIGN PATTERN: Domain-Driven Design (DDD)
 * - Order is an ENTITY (has unique identity - orderId)
 * - OrderItem might be a VALUE OBJECT (identified by parent Order)
 * - Rich domain models contain behavior, not just data
 */
public class Order {

    // ===================================
    // FIELDS (Entity State)
    // ===================================

    /**
     * Unique identifier for this order.
     * In real app: would be auto-generated by database
     */
    private String orderId;

    /**
     * ID of the customer who placed the order
     */
    private String customerId;

    /**
     * List of items in this order
     */
    private List<OrderItem> items;

    /**
     * Total price of the order
     * DESIGN CHOICE: Calculated field vs stored field?
     * - Calculated: sum(items.price) - always accurate, but slower
     * - Stored: saved to DB - faster reads, but can become stale
     * - For financial data: often stored for audit trail
     */
    private BigDecimal totalAmount;

    /**
     * Order status in the workflow
     * This is INTERNAL state - might not be exposed in create request DTO
     */
    private OrderStatus status;

    /**
     * When the order was created
     * IMPORTANT: Set by system, not by client request
     */
    private LocalDateTime createdAt;

    /**
     * Internal notes (not exposed via API)
     * Example of domain model having more data than DTO
     */
    private String internalNotes;

    // ===================================
    // CONSTRUCTORS
    // ===================================

    /**
     * Default constructor (required by Jackson for deserialization)
     */
    public Order() {
    }

    /**
     * Constructor for creating new orders
     * DESIGN PATTERN: Factory method might be better here
     */
    public Order(String customerId, List<OrderItem> items) {
        this.customerId = customerId;
        this.items = items;
        this.status = OrderStatus.PENDING;
        this.createdAt = LocalDateTime.now();
        this.totalAmount = calculateTotal();
    }

    // ===================================
    // BUSINESS LOGIC (Domain Behavior)
    // ===================================

    /**
     * Calculate total amount from items.
     * This is BUSINESS LOGIC that belongs in the domain model.
     *
     * DESIGN PATTERN: Domain logic stays in domain model
     * BAD: Calculating this in Controller or DTO
     * GOOD: Encapsulated here
     */
    private BigDecimal calculateTotal() {
        if (items == null || items.isEmpty()) {
            return BigDecimal.ZERO;
        }
        return items.stream()
                .map(item -> item.getPrice().multiply(BigDecimal.valueOf(item.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
    }

    /**
     * Validate order before processing.
     * Business rule: Order must have at least one item.
     *
     * DESIGN PATTERN: Validation in domain model ensures invariants
     */
    public boolean isValid() {
        return customerId != null && !customerId.isBlank()
                && items != null && !items.isEmpty()
                && items.stream().allMatch(OrderItem::isValid);
    }

    /**
     * Confirm the order (state transition).
     * DESIGN PATTERN: Domain methods for state changes
     */
    public void confirm() {
        if (this.status == OrderStatus.PENDING) {
            this.status = OrderStatus.CONFIRMED;
        } else {
            throw new IllegalStateException("Cannot confirm order in status: " + this.status);
        }
    }

    // ===================================
    // GETTERS AND SETTERS
    // ===================================
    // In real projects, use Lombok @Data to generate these
    // For learning, we write them explicitly to understand what they do

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public List<OrderItem> getItems() {
        return items;
    }

    public void setItems(List<OrderItem> items) {
        this.items = items;
        this.totalAmount = calculateTotal(); // Recalculate when items change
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getInternalNotes() {
        return internalNotes;
    }

    public void setInternalNotes(String internalNotes) {
        this.internalNotes = internalNotes;
    }

    // ===================================
    // EQUALS, HASHCODE, TOSTRING
    // ===================================
    // Important for:
    // - equals/hashCode: Using Order in Collections (Set, Map)
    // - toString: Debugging and logging

    @Override
    public String toString() {
        return "Order{" +
                "orderId='" + orderId + '\'' +
                ", customerId='" + customerId + '\'' +
                ", items=" + items +
                ", totalAmount=" + totalAmount +
                ", status=" + status +
                ", createdAt=" + createdAt +
                '}';
    }
}
