package com.example.orderservice.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * ORDER RESPONSE DTO
 * ==================
 *
 * Returned to the client after creating an order.
 *
 * WHY A SEPARATE RESPONSE DTO?
 * =============================
 * 1. Request and Response shapes differ:
 *    - Request: customerId + items
 *    - Response: orderId + customerId + items + totalAmount + status + createdAt
 *
 * 2. Response includes system-generated fields:
 *    - orderId (generated by service)
 *    - totalAmount (calculated by service)
 *    - status (set by service)
 *    - createdAt (timestamp set by service)
 *
 * 3. Security: Don't expose internal fields
 *    - internalNotes is NOT in response DTO
 *    - Even though it's in domain model
 *
 * DTO MAPPING STRATEGIES:
 * =======================
 * 1. Manual mapping (what we're doing now for learning):
 *    OrderResponse response = new OrderResponse();
 *    response.setOrderId(order.getOrderId());
 *    response.setCustomerId(order.getCustomerId());
 *    ...
 *
 * 2. MapStruct (production-grade):
 *    @Mapper interface that generates mapping code at compile-time
 *    Fast, type-safe, maintainable
 *
 * 3. ModelMapper (runtime reflection):
 *    modelMapper.map(order, OrderResponse.class)
 *    Easy but slower due to reflection
 */
public class OrderResponse {

    private String orderId;
    private String customerId;
    private List<OrderItemResponse> items;
    private BigDecimal totalAmount;
    private String status; // Serialized as string for JSON
    private LocalDateTime createdAt;

    // Constructors
    public OrderResponse() {
    }

    // Getters and Setters
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public List<OrderItemResponse> getItems() {
        return items;
    }

    public void setItems(List<OrderItemResponse> items) {
        this.items = items;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public String toString() {
        return "OrderResponse{" +
                "orderId='" + orderId + '\'' +
                ", customerId='" + customerId + '\'' +
                ", items=" + items +
                ", totalAmount=" + totalAmount +
                ", status='" + status + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
